# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gAV_f8zoGRIhPFh5zHuKctAZqCYzv-js
"""

#Attendance Checker program
print ("===Student Attendance Checker===")

name = input ("enter student name:")
course = input("Enter student course :")

try:
  total_classes = int (input("enter total classes held:"))
  attended_classes = int (input("enter classes attended:"))


  if total_classes <= 0 :
    print("total classes must be grater than 0 :")
  elif attended_classes < 0 or attended_classes > total_classes:
    print("invalid attend classes value.")
  else:
      attendance_percentage = (attended_classes  / total_classes)*100
      print (" result....")
      print ("name:",name)
      print ("course:",course)
      print ("attendance percentage:",round(attendance_percentage,2),"%")
      if attendance_percentage >=75:
          print ("allow for extra")
      else:
          print ("not allowed for exam")
except ValueError:
  print ("please enter valid numeric values for classses")